<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from "vue";
import { Bot, ChevronUp, ChevronDown, Plus, Send, Trash2, History } from "lucide-vue-next";
import { api, session } from "../api";
const props=defineProps<{projectId:number;workflowId?:number;workflowName:string;triggerType:string;triggerGlob:string;canvas:any}>();
const emit=defineEmits<{apply:[canvas:any,revision:number];checkpoint:[]}>();
const open=ref(false),height=ref(330),providers=ref<any[]>([]),conversations=ref<any[]>([]),active=ref<any>(),messages=ref<any[]>([]),input=ref(""),busy=ref(false),streamText=ref(""),tools=ref<any[]>([]),error=ref("");
const selectedProvider=ref(0),body=ref<HTMLElement>();
const activeTitle=computed(()=>active.value?.title||"AI 自动编排");
async function load(){[providers.value,conversations.value]=await Promise.all([api<any[]>(`/api/ai/providers?project_id=${props.projectId}`),api<any[]>(`/api/projects/${props.projectId}/ai/conversations${props.workflowId?`?workflow_id=${props.workflowId}`:""}`)]);if(!selectedProvider.value&&providers.value[0])selectedProvider.value=providers.value[0].id}
async function create(){if(!selectedProvider.value){error.value="请先在 AI 模型页面添加配置";return}const c=await api<any>(`/api/projects/${props.projectId}/ai/conversations`,{method:"POST",body:JSON.stringify({title:"新会话",provider_id:selectedProvider.value,workflow_id:props.workflowId,canvas:props.canvas})});conversations.value.unshift(c);await choose(c)}
async function choose(c:any){active.value=await api(`/api/projects/${props.projectId}/ai/conversations/${c.id}`);messages.value=active.value.messages||[];selectedProvider.value=active.value.provider_id;open.value=true;scroll()}
async function remove(c:any){if(!confirm("删除此 AI 会话及历史消息？"))return;await api(`/api/projects/${props.projectId}/ai/conversations/${c.id}`,{method:"DELETE"});if(active.value?.id===c.id){active.value=undefined;messages.value=[]}await load()}
async function rename(c:any){const title=prompt("会话名称",c.title);if(!title?.trim())return;await api(`/api/projects/${props.projectId}/ai/conversations/${c.id}`,{method:"PATCH",body:JSON.stringify({title:title.trim()})});c.title=title.trim();if(active.value?.id===c.id)active.value.title=title.trim()}
function scroll(){nextTick(()=>{if(body.value)body.value.scrollTop=body.value.scrollHeight})}
async function listen(signal:AbortSignal){const response=await fetch(`/api/projects/${props.projectId}/ai/conversations/${active.value.id}/stream`,{headers:{Authorization:`Bearer ${session.token}`},signal});if(!response.body)return;const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split("\n\n");buffer=chunks.pop()||"";for(const chunk of chunks){const line=chunk.split("\n").find(x=>x.startsWith("data: "));if(!line)continue;const event=JSON.parse(line.slice(6));if(event.type==="delta")streamText.value+=event.data;if(event.type==="tool")tools.value.push(event.data);if(event.type==="error"){error.value=String(event.data);busy.value=false}if(event.type==="done"){emit("checkpoint");emit("apply",event.data.canvas,event.data.canvas_revision);messages.value.push(event.data.message);streamText.value="";busy.value=false;active.value.canvas_revision=event.data.canvas_revision;active.value.canvas_snapshot=JSON.stringify(event.data.canvas);scroll();return}}}}
async function send(){if(!input.value.trim()||busy.value)return;if(!active.value)await create();if(!active.value)return;error.value="";busy.value=true;streamText.value="";tools.value=[];messages.value.push({role:"user",content:input.value});const content=input.value;input.value="";const controller=new AbortController();listen(controller.signal).catch(e=>{if(e.name!=="AbortError"){error.value=e.message;busy.value=false}});await new Promise(r=>setTimeout(r,80));try{await api(`/api/projects/${props.projectId}/ai/conversations/${active.value.id}/messages`,{method:"POST",body:JSON.stringify({content,canvas:props.canvas,canvas_revision:active.value.canvas_revision||0,workflow_id:props.workflowId,workflow_name:props.workflowName,trigger_type:props.triggerType,trigger_glob:props.triggerGlob})})}catch(e:any){controller.abort();error.value=e.message;busy.value=false}scroll()}
async function stop(){if(!active.value)return;await api(`/api/projects/${props.projectId}/ai/conversations/${active.value.id}/stop`,{method:"POST"});busy.value=false}
function restore(){if(!active.value?.canvas_snapshot)return;emit("checkpoint");emit("apply",JSON.parse(active.value.canvas_snapshot),active.value.canvas_revision)}
function key(e:KeyboardEvent){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}
function resizeStart(e:PointerEvent){const y=e.clientY,h=height.value;const move=(x:PointerEvent)=>height.value=Math.max(240,Math.min(650,h+y-x.clientY));const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)}
function toggle(){open.value=!open.value} async function newFromShortcut(){open.value=true;await create()}
onMounted(()=>{load();window.addEventListener("ai-toggle",toggle);window.addEventListener("ai-new",newFromShortcut)});onUnmounted(()=>{window.removeEventListener("ai-toggle",toggle);window.removeEventListener("ai-new",newFromShortcut)});watch(()=>props.workflowId,async(id)=>{if(id&&active.value&&!active.value.workflow_id){await api(`/api/projects/${props.projectId}/ai/conversations/${active.value.id}`,{method:"PATCH",body:JSON.stringify({workflow_id:id})});active.value.workflow_id=id}await load()})
</script>
<template><section class="ai-panel" :class="{open}" :style="open?{height:height+'px'}:{}"><header @click="open=!open"><Bot/><b>{{activeTitle}}</b><span v-if="busy" class="ai-thinking">正在编排…</span><button class="icon-btn"><ChevronDown v-if="open"/><ChevronUp v-else/></button></header><template v-if="open"><div class="ai-resize" @pointerdown="resizeStart"></div><div class="ai-layout"><aside><div class="ai-provider"><select v-model.number="selectedProvider"><option v-for="p in providers" :value="p.id">{{p.name}} · {{p.model}}</option></select><button class="icon-btn" title="新建会话" @click="create"><Plus/></button></div><button v-for="c in conversations" :key="c.id" :class="{active:active?.id===c.id}" @click="choose(c)" @dblclick="rename(c)"><History/><span>{{c.title}}</span><Trash2 @click.stop="remove(c)"/></button></aside><main class="ai-chat"><div ref="body" class="ai-messages"><div v-if="!active" class="empty"><Bot/><h3>让 AI 编排当前画布</h3><p>AI 只能修改未保存草稿，不会保存或运行工作流。</p><button class="btn small-btn" @click="create">新建会话</button></div><div v-for="m in messages" :class="['ai-message',m.role]"><small>{{m.role==='user'?'你':'AI'}}</small><p>{{m.content}}</p></div><div v-if="streamText" class="ai-message assistant"><small>AI</small><p>{{streamText}}</p></div><div v-if="tools.length" class="ai-tools">工具调用：{{tools.map(x=>x.name).join('、')}}</div><p v-if="error" class="error">{{error}}</p></div><div v-if="active" class="ai-compose"><button class="icon-btn" title="恢复会话画布" @click="restore"><History/></button><textarea v-model="input" rows="2" placeholder="例如：创建一个检查服务器文件后上传并解压的流程" @keydown="key"></textarea><button v-if="busy" class="btn danger" @click="stop">停止</button><button v-else class="btn" :disabled="!input.trim()" @click="send"><Send/></button></div></main></div></template></section></template>
