<script setup lang="ts">
import{onMounted,onUnmounted,ref}from'vue';import{FolderKanban,Plus,ArrowUpRight,Copy}from'lucide-vue-next';import{api}from'../api';import Modal from'../components/Modal.vue';import EmptyState from'../components/EmptyState.vue';
const projects=ref<any[]>([]),showCreate=ref(false),name=ref(''),saving=ref(false),created=ref<any>(),copied=ref(false),error=ref('');
async function load(){projects.value=await api('/api/projects')}
async function create(){saving.value=true;error.value='';try{created.value=await api('/api/projects',{method:'POST',body:JSON.stringify({name:name.value})});showCreate.value=false;name.value='';await load()}catch(e:any){error.value=e.message}finally{saving.value=false}}
async function copy(){await navigator.clipboard.writeText(created.value.token);copied.value=true;setTimeout(()=>copied.value=false,1500)}
function key(e:KeyboardEvent){if(e.key.toLowerCase()==='n'&&!['INPUT','TEXTAREA','SELECT'].includes((document.activeElement?.tagName||'')))showCreate.value=true}
onMounted(()=>{load();document.addEventListener('keydown',key)});onUnmounted(()=>document.removeEventListener('keydown',key));
</script>
<template><div class="page-heading"><div><span class="eyebrow">交付空间</span><h1>项目</h1><p>管理 CI 产物、访问 Token 与部署工作流。</p></div><button class="btn" @click="showCreate=true"><Plus/>新建项目</button></div><div class="project-grid"><router-link v-for="p in projects" :key="p.id" :to="`/projects/${p.id}`" class="card project-card"><div class="card-icon"><FolderKanban/></div><div class="grow"><h3>{{p.name}}</h3><p>创建于 {{new Date(p.created_at).toLocaleDateString()}}</p></div><ArrowUpRight class="arrow"/></router-link><EmptyState v-if="!projects.length" title="还没有项目" text="创建项目后即可接收自动上传的产物。"><button class="btn" @click="showCreate=true"><Plus/>新建项目</button></EmptyState></div><Modal v-model="showCreate" title="新建项目" description="项目创建后会生成唯一访问 Token。"><form @submit.prevent="create"><label>项目名称<input v-model="name" autofocus required maxlength="150" placeholder="例如：Web 控制台"></label><p v-if="error" class="error">{{error}}</p><div class="panel-actions"><button type="button" class="btn secondary" @click="showCreate=false">取消</button><button class="btn" :disabled="saving">{{saving?'创建中…':'创建项目'}}</button></div></form></Modal><Modal :model-value="!!created" title="请立即保存项目 Token" description="该 Token 仅显示一次，关闭后无法再次查看。" :locked="true"><div class="token-box"><code>{{created?.token}}</code><button class="icon-btn" title="复制" @click="copy"><Copy/></button></div><p class="muted">Token 可用于上传和直链下载。请保存到 CI Secret 或安全的密码管理器中。</p><div class="panel-actions"><button class="btn" @click="created=undefined">{{copied?'已复制':'我已保存'}}</button></div></Modal></template>
